spring:
  jpa:
    # 쿼리 실행 구문 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  issuer: yunjin8931@gmail.com #이슈 발급자
  secret_key: springboot-blog-skey # 비밀키
